### ISSUE TITLE
Проект: Базовая линия (baseline)

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#1002]
### Описание проблемы

При выпуске любого приложения на 1С необходимо использовать версионирование проекта.
Существуют разные стратегии версионирования, но основная стратегия в мире - это [SemVer - Семантическое версионирование](https://semver.org/lang/ru/). В мире 1С используется именно SemVer с добавлением в начало еще одной цифры совместимости базы данных, идущей в комплекте с приложением - "редакция":

| SemVer | 1С-приложения |
|---------|------------------|
| -- | Редакция |
| Major | Подредация |
| Minor | Версия |
| Patch | Сборка |

Подробнее тут: [Нумерация редакций и версий](https://its.1c.ru/db/v8std/content/483/hdoc) и объяснение допустимости изменений в стандарте [Обеспечение совместимости библиотек](https://its.1c.ru/db/v8std#content:644:hdoc) и [Общие сведения о выпуске конфигураций](https://its.1c.ru/db/v8std#content:484:hdoc), которые, в общем, справедливы для любого приложения 1С, если на его основе другие компании делают свои доработки (например "типовые конфигурации от 1С").

Так же есть стандарт регламентирующий процесс переноса данных между таблицами БД и удаление таблиц: [Удаление устаревших объектов метаданных из конфигурации](https://its.1c.ru/db/v8std#content:534:hdoc). Нельзя в рамках одной версии удалять таблицы или поля таблиц.

Поведение [предопределенных элементов при копировании](https://its.1c.ru/db/metod8dev/content/2327/hdoc) между метаданными, описывающее сравнение-объединение и обновление их в ИБ.

Так же смена UUID (уникальный идентификатор) в объекте метаданных - приводит удалению и добавлению таблицы/колонки в  базе данных 1С. 

Существуют другие паттерны изменения метаданных которые могут привести к потери пользовательских данных:
- Снятие флага "Иерархический" у справочников и ПВХ
- Удаление из состава "владельцев" в справочниках
- Удаление типов ПВХ  из состава, смена типа справочника расширенных значений ПВХ
- Сокращение типов регистров проведения в документе - приведет удалению или неактуальности регистров (? выяснить поведение в Платформе)
- Сокращение состава определяемых типов
- ? еще?

Возникает необходимость:
1. Контроль потери пользовательских данных, без миграции данных через "Удалить"
2. Контроль программного интерфейса (экспортных функций) API
3. Необходимо учитывать схему версионирования приложений 1С когда разрешено удалять/менять API или в БД приложения.

Этот контроль возможен на основе какой-то предыдущей выпущенной версии приложения 1С.

### Описание решения проблемы

Хотелось бы при разработке выполнять онлайн-контроль текущей версии относительно какой-то базовой выпущенной версии.

Очевидно, что без внешней информации о "базовой версии" приложения, с которой необходимо сравнивать, такой контроль сделать невозможно.

### Что предлагается сделать

Рассмотрим задачи которые необходим реализовать. 

#### Дополнительные механизмы

- Сохранение "снимка" (snapshot) текущего программного интерфейса API по текущему приложению
- Сохранение "снимка" текущей структуры БД

Отметим отдельно, что систему хранения этих снимков в рамках этого проекта, реализовывать не будем.
Но возможны следующие варианты хранения:
- В новом механизме snapshot-ов в ЕДТ (необходимо рассмотреть сценарии как это возможно использовать в реальных процессах разработки)
- Внешнее хранение на каком-либо ресурсе (например, CI собирает новую релизную версию приложения и выполняет обновление снимков БД и API при публикации релиза для пользователей) - текущая master/main-ветка будет скачивать эти снимки и выполнять дальнейшие проверки с текущей версией приложения.

#### Проверки 

- Контроль объектов метаданных - на предмет потери данных, с учетом правильного переноса в рамках разных версий
- Контроль API приложения, с учетом "устаревших" и правильных версий

Реализовать задачи:
- #712
- #109
- #232
- #234
- #235
- #632
- #633
- #634
- #135
- #137
- #136
- #328
- #478

### Примеры модели данных хранения снимков приложения

Необходимо определить какие данные сохранять в снимок 

TODO: проанализировать инструменты БСП и ERP по контролю.

#### Модель данных снимка API

Данные должны хранить полные имена модулей, методов, типов параметров и возвращаемых значений функций

```yml
ApiStructure:
  version: 2.5.8.157
  modules:
    CommonModule.ОбщегоНазначения:
      methods:
        - name: ЗначениеРеквизитаОбъекта
          parameters:
            - name: Ссылка
              types: 
                - name: AnyRef
                  containTypes: []
                  fields: []
          returnTypes:
            - name: Arbitrary
    CommonModule.ОбщегоНазначенияКлиент:
      methods:

```

#### Модель данных снимка БД

Снимок базы данных должен хранить имена таблиц, uuid, и типы полей

```yml
DbStructure:
  version: 2.5.8.157
  catalogs:
    - name: Товары
      uuid: df67as-asdf87-asdfas6-daf98656d
      fields:
        - name: Parent
          uuid: 
          types: [CatalogRef.Товары]
        - name: Owner
          uuid:
          types: []
        - name: Артикул
          uuid: afsd87asd-dasdf79887-lak675-da87sdf
          types:
            - String
      tables:
      predefined:
    - name: Валюты
      uuid: ...
```

TODO дополнить модели, при необходимости.
